### ISSUE TITLE
Instructions on doc site unclear, can't get anything to run or compile correctly.

### ISSUE THREAD

**Issue by JakeHadley** [philippj/SteamworksPy#74]
I've been trying to get to a point where this python library is usable, and have been unsuccessful thus far. I've followed the docs [here](https://philippj.github.io/SteamworksPy/) with no success at all. It's not clear where files are supposed to go and from where certain commands are meant to be ran. I tried downloading the precompiled libraries but I don't know where to put them. 

I even downloaded the example zip that you provided from [here](https://github.com/philippj/SteamworksPy/issues/66#issuecomment-810296916) and got the same errors on that ticket. I run the test.py file and get this error:
```
PS C:\<user>\SteamworksPyTest\SteamworksPyTest> & C:/<user>AppData/Local/Programs/Python/Python310/python.exe c:/<user>Downloads/SteamworksPyTest/SteamworksPyTest/test.py
Traceback (most recent call last):
  File "c:\<user>\SteamworksPyTest\SteamworksPyTest\test.py", line 7, in <module>
    steamworks.initialize()
  File "c:\<user>\SteamworksPyTest\SteamworksPyTest\steamworks\__init__.py", line 147, in initialize
    result = self._cdll.SteamInit()
OSError: exception: access violation reading 0x0000000000000000
```

I'm logged into steam and it's open, and I'm on Windows 11 x64

So I'm kind of at a loss as to where to go from here. This seems to be a super useful library for what I'm trying to accomplish. Any help here would be greatly appreciated. Thanks!

**Comment by philippj** [comment]
The example you have linked contains a self-contained example with all files properly placed and ready for execution. I am not able to replicate your issue with either Win10 oder Win11. Do you happen to have installed Python using the Windows store?

**Comment by JakeHadley** [comment]
Yeah that's why I'm frustrated haha. There's no reason that it shouldn't work 

And no, I installed it from the official links. Is there a way to set up python a different way to test if that is what is causing the issue?

I also have WSL setup. Do you have a self contained project for Linux I could try?

**Comment by philippj** [comment]
There is no self-contained project, the examples work out of the box for Windows and Linux as far as I know. I test personally on Ubuntu 20 LTS.
