### ISSUE TITLE
Small issue, possible working example

### ISSUE THREAD

**Issue by BMaxV** [philippj/SteamworksPy#86]
Hi! Thanks for making this tool, I have a small problem.

I am using panda3d.

I did not custom build, I used the release prebuilt for linux and I am getting the error below.

This doesn't really line up with the source so I'm not sure what's happening. Should I just build from source instead?

```
Traceback (most recent call last):
  File "panda.py", line 45, in <module>
  File "panda.py", line 40, in main
  File "panda.py", line 36, in __init__
  File "panda.py", line 14, in __init__
  File "steamworks", line 50, in __init__
  File "steamworks", line 93, in _initialize
  File "steamworks", line 106, in _load_steamworks_api
  File "ctypes", line 386, in __getattr__
  File "ctypes", line 391, in __getitem__
AttributeError: .../PandaCompatTest/build/manylinux2014_x86_64/SteamworksPy.so: undefined symbol: SteamShutdown
```

I have created an example repository https://github.com/BMaxV/panda3d_steamworks_example

**Comment by BMaxV** [comment]
Ok yeah, just had to be built, the docs worked. I was mislead by the "release" :)
