### ISSUE TITLE
function 'GetAnalogActionData'

### ISSUE THREAD

**Issue by hamsandvich** [philippj/SteamworksPy#87]
This is what im getting after setting up everything and using the Basic Example.

Traceback (most recent call last):
  File "c:\Users\logan\Desktop\SteamWorks Testing\test.py", line 22, in <module>
    steamworks = STEAMWORKS()
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\site-packages\steamworks-2.0.0-py3.10.egg\steamworks\__init__.py", line 52, in __init__
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\site-packages\steamworks-2.0.0-py3.10.egg\steamworks\__init__.py", line 104, in _initialize
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\site-packages\steamworks-2.0.0-py3.10.egg\steamworks\__init__.py", line 117, in _load_steamworks_api
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\logan\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'GetAnalogActionData' not found. Did you mean: 'GetAnalogActionHandle'?

Is this a issue cause im using Python 3.10.10?

**Comment by hamsandvich** [comment]
<img width="1356" alt="Code_4L3Kdm8anx" src="https://user-images.githubusercontent.com/72324766/230746123-f325ef0d-6dbf-4b8d-a906-3bd61cc997b9.png">

**Comment by hamsandvich** [comment]
Interesting. 

Something must of broke in the newer release.

When i downgraded to https://github.com/philippj/SteamworksPy/releases/tag/1.6.4 

Everything started working.

**Comment by BigMeatyClaws** [comment]
For anyone still looking, it's because the method call is deprecated.
https://partner.steamgames.com/doc/api/ISteamController
